#define ENCLAVE_FILE "TestEnclave.signed.dll" // Remove the 'L' prefix

#include "sgx_urts.h"         // SGX untrusted runtime library
#include "TestEnclave_u.h"    // Updated to match
#include <stdio.h>
#include <stdint.h>

int main() {
    sgx_enclave_id_t eid;           // Enclave ID
    sgx_status_t ret = SGX_SUCCESS; // SGX status
    sgx_launch_token_t token = { 0 }; // Launch token
    int updated = 0;

    uint32_t random_number = 0; // Variable to store the random number

    // Create the enclave
    ret = sgx_create_enclave(ENCLAVE_FILE, SGX_DEBUG_FLAG, &token, &updated, &eid, NULL);
    if (ret != SGX_SUCCESS) {
        printf("\nApp: error %#x, failed to create enclave.\n", ret);
        return -1;
    }

    // Call ECALL to generate a random number in the enclave
    ret = ecall_generate_random(eid, &random_number);
    if (ret != SGX_SUCCESS) {
        printf("\nApp: error %#x during ECALL.\n", ret);
        sgx_destroy_enclave(eid);
        return -1;
    }

    printf("\nApp: Random number generated by enclave: %u\n", random_number);

    // Destroy the enclave when all ECALLs are finished
    if (SGX_SUCCESS != sgx_destroy_enclave(eid)) {
        printf("\nApp: error, failed to destroy enclave.\n");
    }

    getchar(); // Wait for user input before closing
    return 0;
}
